### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by KenMizz** [Earthcomputer/EnchantmentCracker#146]
This happened when I try to calculate my second seed

Log:
```java
java.lang.OutOfMemoryError: Java heap space
        at enchcracker.IntArray.addToList(IntArray.java:14)
        at enchcracker.IntArray.addAll(IntArray.java:41)
        at enchcracker.cracker.JavaSingleSeedCracker.lambda$firstInput$0(JavaSingleSeedCracker.java:111)
        at enchcracker.cracker.JavaSingleSeedCracker$$Lambda$35/1172302804.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

[2020-04-01 14:12:36] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
        at enchcracker.IntArray.addToList(IntArray.java:14)
        at enchcracker.IntArray.addAll(IntArray.java:41)
        at enchcracker.cracker.JavaSingleSeedCracker.lambda$firstInput$0(JavaSingleSeedCracker.java:111)
        at enchcracker.cracker.JavaSingleSeedCracker$$Lambda$35/1172302804.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is REQUIRED for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 2GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have more than 2GB of RAM to spare.
4. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues
```
Im running on
![image](https://user-images.githubusercontent.com/16635884/78172443-14831100-7424-11ea-9ead-b1b76bde3bcc.png)

**Comment by KenMizz** [comment]
I'm running the cracker on the latest build from sources

**Comment by Earthcomputer** [comment]
Can you please send the **full** log?

**Comment by KenMizz** [comment]
I can't reproduce the problem anymore, seems like the issue has been magically fix?
