### ISSUE TITLE
Issue in 1.4.1

### ISSUE THREAD

**Issue by CPTProgrammer** [Earthcomputer/EnchantmentCracker#150]
When I open the BAT file, it throw a NullPointerException error.
Log file:
> [2020-04-08 15:10:30] [/INFO]: Enchantment cracker version V1.4
[2020-04-08 15:10:30] [/INFO]: System details:
[2020-04-08 15:10:30] [/INFO]: OS = Windows 10 10.0
[2020-04-08 15:10:30] [/INFO]: Arch (either OS/Java) = amd64
[2020-04-08 15:10:30] [/INFO]: Java = 1.8.0_241
[2020-04-08 15:10:30] [/INFO]: Java arch = 64
[2020-04-08 15:10:32] [/SEVERE]: Exception creating frame
java.lang.NullPointerException
	at enchcracker.swing.StyledFrameMinecraft.<init>(StyledFrameMinecraft.java:24)
	at enchcracker.EnchCrackerWindow.<init>(EnchCrackerWindow.java:157)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:106)

**Comment by CPTProgrammer** [comment]
The close button file is "null"

**Comment by Earthcomputer** [comment]
Why are you using 1.4.1? Please update to 1.4.6, the bug may have been fixed.

**Comment by CPTProgrammer** [comment]
> Why are you using 1.4.1? Please update to 1.4.6, the bug may have been fixed.

Does 1.4.6 support Minecraft 1.8.8?

**Comment by Earthcomputer** [comment]
Yes, it supports all versions

**Comment by CPTProgrammer** [comment]
Thanks
:)
