### ISSUE TITLE
java.lang.OutOfMemoryError:

### ISSUE THREAD

**Issue by SaleGepa** [Earthcomputer/EnchantmentCracker#162]
[2020-05-08 18:00:03] [/INFO]: Enchantment cracker version V1.4.4
[2020-05-08 18:00:03] [/INFO]: System details:
[2020-05-08 18:00:03] [/INFO]: OS = Windows 10 10.0
[2020-05-08 18:00:03] [/INFO]: Arch (either OS/Java) = amd64
[2020-05-08 18:00:03] [/INFO]: Java = 1.8.0_251
[2020-05-08 18:00:03] [/INFO]: Java arch = 64
[2020-05-08 18:00:33] [/INFO]: Added info, b = 15, s1 = 6, s2 = 10, s3 = 30
[2020-05-08 18:00:33] [/INFO]: Cracking first input using 12 threads (including main thread)
[2020-05-08 18:00:38] [/INFO]: Done in 4.15 seconds
[2020-05-08 18:00:38] [/INFO]: Reduced possible seeds to 44040339
[2020-05-08 18:00:52] [/INFO]: Added info, b = 14, s1 = 9, s2 = 19, s3 = 28
[2020-05-08 18:00:52] [/INFO]: Reduced possible seeds to 62481
[2020-05-08 18:01:04] [/INFO]: Added info, b = 13, s1 = 7, s2 = 15, s3 = 26
[2020-05-08 18:01:04] [/INFO]: Reduced possible seeds to 1935
[2020-05-08 18:01:16] [/INFO]: Added info, b = 12, s1 = 7, s2 = 14, s3 = 24
[2020-05-08 18:01:16] [/INFO]: Reduced possible seeds to 31
[2020-05-08 18:01:28] [/INFO]: Added info, b = 9, s1 = 6, s2 = 10, s3 = 18
[2020-05-08 18:01:28] [/INFO]: Reduced possible seeds to 8
[2020-05-08 18:01:38] [/INFO]: Added info, b = 6, s1 = 3, s2 = 9, s3 = 12
[2020-05-08 18:01:38] [/INFO]: Reduced possible seeds to 2
[2020-05-08 18:01:49] [/INFO]: Added info, b = 3, s1 = 3, s2 = 5, s3 = 10
[2020-05-08 18:01:49] [/INFO]: Reduced possible seeds to 1
[2020-05-08 18:02:15] [/INFO]: Reset the cracker
[2020-05-08 18:02:27] [/INFO]: Added info, b = 15, s1 = 5, s2 = 13, s3 = 30
[2020-05-08 18:02:27] [/INFO]: Cracking first input using 12 threads (including main thread)
[2020-05-08 18:02:32] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
	at enchcracker.IntArray.addToList(IntArray.java:14)
	at enchcracker.IntArray.addAll(IntArray.java:41)
	at enchcracker.cracker.JavaSingleSeedCracker.lambda$firstInput$0(JavaSingleSeedCracker.java:111)
	at enchcracker.cracker.JavaSingleSeedCracker$$Lambda$30/1670147904.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[2020-05-08 18:02:33] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
	at enchcracker.IntArray.addToList(IntArray.java:14)
	at enchcracker.IntArray.addAll(IntArray.java:41)
	at enchcracker.cracker.JavaSingleSeedCracker.lambda$firstInput$0(JavaSingleSeedCracker.java:111)
	at enchcracker.cracker.JavaSingleSeedCracker$$Lambda$30/1670147904.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[2020-05-08 18:02:33] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space

**Comment by Earthcomputer** [comment]
Looks like you are using version 1.4.4, please upgrade to version 1.4.6

**Comment by SaleGepa** [comment]
How's work new xp bar added in client put xp before dummu or after?

**Comment by Earthcomputer** [comment]
I'm afraid I don't know what you're talking about, there is no new xp bar.

**Comment by SaleGepa** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/65033592/81430929-99b6bf80-9160-11ea-9b54-bf4992dd52e6.png)
this
