### ISSUE TITLE
OutOfMemoryError on MacOS

### ISSUE THREAD

**Issue by 5space** [Earthcomputer/EnchantmentCracker#19]
When I initially add info on MacOS and the cracker has to scan through all 2^32 seeds, about a third of the way through it crashes with an OutOfMemoryError:

[2018-05-07 22:30:39] [/INFO]: System details:
[2018-05-07 22:30:39] [/INFO]: OS = Mac OS X 10.12.6
[2018-05-07 22:30:39] [/INFO]: Arch (either OS/Java) = x86_64
[2018-05-07 22:30:39] [/INFO]: Java = 1.8.0_144
[2018-05-07 22:30:39] [/INFO]: Java arch = 64
[2018-05-07 22:30:39] [/WARNING]: Failed to load native enchcracker library! Using the Java version instead
java.lang.UnsatisfiedLinkError: no enchcracker in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:18)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:106)

[2018-05-07 22:31:03] [/INFO]: Added info, b = 15, s1 = 5, s2 = 13, s3 = 30
[2018-05-07 22:33:14] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at enchcracker.JavaSingleSeedCracker.firstInput(JavaSingleSeedCracker.java:70)
	at enchcracker.EnchCrackerWindow$3.lambda$1(EnchCrackerWindow.java:237)
	at enchcracker.EnchCrackerWindow$3$$Lambda$48/2104610869.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Earthcomputer** [comment]
Try version 1.1.4
