### ISSUE TITLE
can't load the client at all 

### ISSUE THREAD

**Issue by fibular** [Earthcomputer/EnchantmentCracker#25]
:?

**Comment by Earthcomputer** [comment]
Please be more specific

**Comment by fibular** [comment]
[2018-05-28 15:27:18] [/INFO]: System details:
[2018-05-28 15:27:18] [/INFO]: OS = Windows 10 10.0
[2018-05-28 15:27:18] [/INFO]: Arch (either OS/Java) = x86
[2018-05-28 15:27:18] [/INFO]: Java = 1.8.0_171
[2018-05-28 15:27:18] [/INFO]: Java arch = 32
[2018-05-28 15:27:18] [/WARNING]: Failed to load native enchcracker library! Using the Java version instead
java.lang.UnsatisfiedLinkError: no enchcracker in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:18)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:106)

[2018-05-28 15:27:19] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.Arrays.copyOf(Unknown Source)
	at java.util.ArrayList.grow(Unknown Source)
	at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
	at java.util.ArrayList.ensureCapacity(Unknown Source)
	at enchcracker.JavaSingleSeedCracker.initCracker(JavaSingleSeedCracker.java:39)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:108)

This is what my log says, after extracting the zip file to my desktop, i then open the folder, attempt to run the bat file. The bat runs then instantly closes, and nothing is loaded. When opening the jar, it says: C:\Users\(my name)\Desktop\Newfolder\enchcracker\enchcracker.dll: Can't load AMD 64-bit.dll on a IA 32-bit platform
Probably cause: you are using 32-bit java or a 32-bit system. You need 64-bit (I have a system 64 bit and java 64 bit so i'm not sure why it's saying this)

**Comment by Earthcomputer** [comment]
The log says that Java ran out of memory. You need to allocate more memory
