### ISSUE TITLE
Why does the program crash when I run it

### ISSUE THREAD

**Issue by wangxiao20485** [Earthcomputer/EnchantmentCracker#256]
When I use enchantmentcracker, I calculate that the first XP seed starts to calculate, and the second XP seed starts to calculate. When the first progress bar reaches 98%, the program crashes.
Program running log as follows
[2021-04-04 16:01:36] [/INFO]: Enchantment cracker version V1.5.1
[2021-04-04 16:01:36] [/INFO]: System details:
[2021-04-04 16:01:36] [/INFO]: OS = Windows 10 10.0
[2021-04-04 16:01:36] [/INFO]: Arch (either OS/Java) = amd64
[2021-04-04 16:01:36] [/INFO]: Java = 1.8.0_281
[2021-04-04 16:01:36] [/INFO]: Java arch = 64
[2021-04-04 16:02:25] [/INFO]: Added info, b = 15, s1 = 4, s2 = 11, s3 = 30
[2021-04-04 16:02:25] [/INFO]: Cracking first input using 2 threads (including main thread)
[2021-04-04 16:03:23] [/INFO]: Done in 58.29 seconds
[2021-04-04 16:03:23] [/INFO]: Reduced possible seeds to 75497697
[2021-04-04 16:03:46] [/INFO]: Added info, b = 14, s1 = 4, s2 = 15, s3 = 28
[2021-04-04 16:03:48] [/INFO]: Reduced possible seeds to 1848902
[2021-04-04 16:04:14] [/INFO]: Added info, b = 13, s1 = 5, s2 = 14, s3 = 26
[2021-04-04 16:04:14] [/INFO]: Reduced possible seeds to 28017
[2021-04-04 16:04:38] [/INFO]: Added info, b = 12, s1 = 3, s2 = 8, s3 = 24
[2021-04-04 16:04:38] [/INFO]: Reduced possible seeds to 211
[2021-04-04 16:05:01] [/INFO]: Added info, b = 11, s1 = 5, s2 = 8, s3 = 22
[2021-04-04 16:05:01] [/INFO]: Reduced possible seeds to 13
[2021-04-04 16:05:22] [/INFO]: Added info, b = 10, s1 = 3, s2 = 9, s3 = 20
[2021-04-04 16:05:22] [/INFO]: Reduced possible seeds to 1
[2021-04-04 16:06:02] [/INFO]: Reset the cracker
[2021-04-04 16:06:10] [/INFO]: Added info, b = 9, s1 = 2, s2 = 12, s3 = 18
[2021-04-04 16:06:10] [/INFO]: Cracking first input using 2 threads (including main thread)
[2021-04-04 16:07:12] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
        at enchcracker.cracker.JavaSingleSeedCracker.firstInput(JavaSingleSeedCracker.java:143)
        at enchcracker.EnchCrackerWindow.lambda$null$1(EnchCrackerWindow.java:336)
        at enchcracker.EnchCrackerWindow$$Lambda$32/536052783.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

Failed to launch enchcracker!
1. Ensure you have installed Java correctly and that Java is in your PATH.
2. 64-bit Java is preferred for enchcracker. This catches a lot of people out. To check your Java version, run "java -version".
3. 1GB of RAM is a minimum requirement. enchcracker will fail to start if you don't have at least 1GB of RAM to spare.
4. Ensure that you have properly extracted enchcracker to a folder and are not running from the zip file.
5. Ensure that you extracted it into a normal directory, and not directly into the C drive or Program Files.
6. If you still think this is an error, please report it to https://github.com/Earthcomputer/EnchantmentCracker/issues

**Comment by Hexicube** [comment]
You started the second search with a 9 shelf input, looks like you had it ready but then got told first search was done and accidentally started it off.
