### ISSUE TITLE
The Program says that i have to use a 64 bit version, instead of a 32 bit. But i am using the 64bit

### ISSUE THREAD

**Issue by uncledeath292** [Earthcomputer/EnchantmentCracker#26]
[2018-06-06 21:50:10] [/INFO]: System details:
[2018-06-06 21:50:10] [/INFO]: OS = Windows 10 10.0
[2018-06-06 21:50:10] [/INFO]: Arch (either OS/Java) = x86
[2018-06-06 21:50:10] [/INFO]: Java = 1.8.0_171
[2018-06-06 21:50:10] [/INFO]: Java arch = 32
[2018-06-06 21:50:11] [/WARNING]: Failed to load native enchcracker library! Using the Java version instead
java.lang.UnsatisfiedLinkError: C:\Users\Jacob\OneDrive\Desktop\Things\enchcracker\enchcracker\enchcracker.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:18)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:106)

**Comment by uncledeath292** [comment]
Ignore this i just reinstalled java and it fixed
