### ISSUE TITLE
Please Help i dont understand

### ISSUE THREAD

**Issue by DeathDaphy** [Earthcomputer/EnchantmentCracker#273]
An unexpected error occurred
java.lang.ArithmeticException: / by zero
	at enchcracker.cracker.JavaSingleSeedCracker.firstInput(JavaSingleSeedCracker.java:55)
	at enchcracker.EnchCrackerWindow.lambda$null$1(EnchCrackerWindow.java:336)
	at java.lang.Thread.run(Unknown Source
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/7576544/enchcracker.log)
)

**Comment by SeizureSaladd** [comment]
it is trying to divide by 0 lol

**Comment by Earthcomputer** [comment]
oops
