### ISSUE TITLE
Please help me. How do I fix this?

### ISSUE THREAD

**Issue by 1cyM1nt000** [Earthcomputer/EnchantmentCracker#274]
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/7578280/enchcracker.log)

**Comment by 1cyM1nt000** [comment]
This one:
[2021-11-21 22:23:11] [/INFO]: Reset the cracker
[2021-11-21 22:24:25] [/INFO]: Added info, b = 15, s1 = 4, s2 = 6, s3 = 30
[2021-11-21 22:24:25] [/INFO]: Cracking first input using 2 threads (including main thread)
[2021-11-21 22:26:48] [/INFO]: Done in 143.21 seconds
[2021-11-21 22:26:48] [/INFO]: Reduced possible seeds to 4718570
[2021-11-21 22:27:06] [/INFO]: Added info, b = 14, s1 = 4, s2 = 10, s3 = 28
[2021-11-21 22:27:06] [/INFO]: Reduced possible seeds to 57665
[2021-11-21 22:27:26] [/INFO]: Added info, b = 11, s1 = 6, s2 = 5, s3 = 22
[2021-11-21 22:27:26] [/INFO]: Reduced possible seeds to 2238
[2021-11-21 22:27:50] [/INFO]: Added info, b = 10, s1 = 4, s2 = 7, s3 = 20
[2021-11-21 22:27:50] [/INFO]: Reduced possible seeds to 107
[2021-11-21 22:28:05] [/INFO]: Added info, b = 9, s1 = 3, s2 = 8, s3 = 20
[2021-11-21 22:28:05] [/INFO]: Reduced possible seeds to 1
[2021-11-21 22:28:35] [/INFO]: Reset the cracker
[2021-11-21 22:28:57] [/INFO]: Added info, b = 15, s1 = 6, s2 = 13, s3 = 30
[2021-11-21 22:28:57] [/INFO]: Cracking first input using 2 threads (including main thread)
[2021-11-21 22:31:30] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
	at enchcracker.cracker.JavaSingleSeedCracker.firstInput(JavaSingleSeedCracker.java:143)
	at enchcracker.EnchCrackerWindow.lambda$null$1(EnchCrackerWindow.java:336)
	at enchcracker.EnchCrackerWindow$$Lambda$32/1010544621.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by 1cyM1nt000** [comment]
> The Java vm ran out of memory

How do I fix that?

**Comment by meastromees** [comment]
i have the same problem and i saw some ather people that had the same problem but it was a 1 time thing.bij me it din't go away
[sorry i can't realy spel good inglish]

**Comment by meastromees** [comment]
this is my log
[2021-11-23 11:39:32] [/INFO]: Enchantment cracker version V1.5.1
[2021-11-23 11:39:32] [/INFO]: System details:
[2021-11-23 11:39:32] [/INFO]: OS = Windows 10 10.0
[2021-11-23 11:39:32] [/INFO]: Arch (either OS/Java) = amd64
[2021-11-23 11:39:32] [/INFO]: Java = 1.8.0_311
[2021-11-23 11:39:32] [/INFO]: Java arch = 64
[2021-11-23 11:42:21] [/INFO]: Added info, b = 15, s1 = 5, s2 = 11, s3 = 30
[2021-11-23 11:42:21] [/INFO]: Cracking first input using 2 threads (including main thread)
[2021-11-23 11:43:37] [/INFO]: Done in 76.38 seconds
[2021-11-23 11:43:38] [/INFO]: Reduced possible seeds to 100663118
[2021-11-23 11:44:16] [/INFO]: Added info, b = 14, s1 = 7, s2 = 9, s3 = 28
[2021-11-23 11:44:22] [/INFO]: Reduced possible seeds to 1753838
[2021-11-23 11:44:51] [/INFO]: Added info, b = 13, s1 = 6, s2 = 10, s3 = 26
[2021-11-23 11:44:51] [/INFO]: Reduced possible seeds to 26747
[2021-11-23 11:45:06] [/INFO]: Added info, b = 12, s1 = 2, s2 = 13, s3 = 24
[2021-11-23 11:45:06] [/INFO]: Reduced possible seeds to 95
[2021-11-23 11:45:24] [/INFO]: Added info, b = 9, s1 = 3, s2 = 7, s3 = 18
[2021-11-23 11:45:24] [/INFO]: Reduced possible seeds to 12
[2021-11-23 11:45:41] [/INFO]: Added info, b = 6, s1 = 3, s2 = 8, s3 = 16
[2021-11-23 11:45:41] [/INFO]: Reduced possible seeds to 1
[2021-11-23 11:45:44] [/INFO]: Reset the cracker
[2021-11-23 11:46:07] [/INFO]: Added info, b = 15, s1 = 6, s2 = 15, s3 = 30
[2021-11-23 11:46:07] [/INFO]: Cracking first input using 2 threads (including main thread)
[2021-11-23 11:47:20] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
	at enchcracker.cracker.JavaSingleSeedCracker.firstInput(JavaSingleSeedCracker.java:143)
	at enchcracker.EnchCrackerWindow.lambda$null$1(EnchCrackerWindow.java:336)
	at enchcracker.EnchCrackerWindow$$Lambda$32/866045913.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
