### ISSUE TITLE
Failed to laod native library

### ISSUE THREAD

**Issue by NewErigion** [Earthcomputer/EnchantmentCracker#30]
[2018-07-18 18:40:33] [/INFO]: System details:
[2018-07-18 18:40:34] [/INFO]: OS = Windows 10 10.0
[2018-07-18 18:40:34] [/INFO]: Arch (either OS/Java) = x86
[2018-07-18 18:40:34] [/INFO]: Java = 1.8.0_172
[2018-07-18 18:40:34] [/INFO]: Java arch = 32
[2018-07-18 18:40:34] [/WARNING]: Failed to load native enchcracker library! Using the Java version instead
java.lang.UnsatisfiedLinkError: C:\Users\saba saleemi\Downloads\enchcracker\enchcracker\enchcracker.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:18)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:106)

**Comment by asquared31415** [comment]
The cracker should still work after pressing the ok button, but it may be slightly slower.

**Comment by Earthcomputer** [comment]
You need to follow the instructions and install a 64-bit version of Java.
