### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by loopydoopy123** [Earthcomputer/EnchantmentCracker#317]
[2022-02-25 14:13:26] [/INFO]: Enchantment cracker version V1.6
[2022-02-25 14:13:26] [/INFO]: System details:
[2022-02-25 14:13:26] [/INFO]: OS = Windows 10 10.0
[2022-02-25 14:13:26] [/INFO]: Arch (either OS/Java) = amd64
[2022-02-25 14:13:26] [/INFO]: Java = 1.8.0_301
[2022-02-25 14:13:26] [/INFO]: Java arch = 64
[2022-02-25 14:13:45] [/INFO]: Added info, b = 7, s1 = 3, s2 = 9, s3 = 14
[2022-02-25 14:13:45] [/INFO]: Cracking first input using 12 threads (including main thread)
[2022-02-25 14:13:49] [/SEVERE]: An unexpected error occurred
java.lang.OutOfMemoryError: Java heap space
	at enchcracker.cracker.JavaSingleSeedCracker.firstInput(JavaSingleSeedCracker.java:143)
	at enchcracker.EnchCrackerWindow.lambda$null$1(EnchCrackerWindow.java:391)
	at enchcracker.EnchCrackerWindow$$Lambda$35/1457057004.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Phoenix-Starlight** [comment]
Have you tried giving more memory to minecraft?

**Comment by BraveCaperCat** [comment]
Get more RAM, thats what:
java.lang.OutOfMemoryError
Means

**Comment by BraveCaperCat** [comment]
CLOSE NOW
