### ISSUE TITLE
"Unexpected Error"

### ISSUE THREAD

**Issue by Ynng** [Earthcomputer/EnchantmentCracker#46]
ennchacracker.log:
```
[2019-03-16 13:13:12] [/INFO]: System details:
[2019-03-16 13:13:12] [/INFO]: OS = Windows 10 10.0
[2019-03-16 13:13:12] [/INFO]: Arch (either OS/Java) = amd64
[2019-03-16 13:13:12] [/INFO]: Java = 1.8.0_181
[2019-03-16 13:13:12] [/INFO]: Java arch = 64
[2019-03-16 13:13:35] [/INFO]: Added info, b = 15, s1 = 8, s2 = 11, s3 = 30
[2019-03-16 13:14:10] [/INFO]: Reduced possible seeds to 75498080
[2019-03-16 13:14:35] [/INFO]: Added info, b = 14, s1 = 7, s2 = 13, s3 = 28
[2019-03-16 13:14:36] [/INFO]: Reduced possible seeds to 1996272
[2019-03-16 13:14:47] [/INFO]: Added info, b = 13, s1 = 5, s2 = 13, s3 = 26
[2019-03-16 13:14:47] [/INFO]: Reduced possible seeds to 60614
[2019-03-16 13:15:02] [/INFO]: Added info, b = 12, s1 = 4, s2 = 9, s3 = 24
[2019-03-16 13:15:02] [/INFO]: Reduced possible seeds to 1393
[2019-03-16 13:15:19] [/INFO]: Added info, b = 11, s1 = 5, s2 = 11, s3 = 22
[2019-03-16 13:15:19] [/INFO]: Reduced possible seeds to 42
[2019-03-16 13:15:35] [/INFO]: Added info, b = 10, s1 = 3, s2 = 6, s3 = 20
[2019-03-16 13:15:35] [/INFO]: Reduced possible seeds to 2
[2019-03-16 13:15:48] [/INFO]: Added info, b = 9, s1 = 4, s2 = 11, s3 = 18
[2019-03-16 13:15:48] [/INFO]: Reduced possible seeds to 2
[2019-03-16 13:16:09] [/INFO]: Added info, b = 8, s1 = 6, s2 = 5, s3 = 16
[2019-03-16 13:16:09] [/INFO]: Reduced possible seeds to 1
[2019-03-16 13:16:15] [/INFO]: Reset the cracker
[2019-03-16 13:16:42] [/INFO]: Added info, b = 8, s1 = 5, s2 = 9, s3 = 16
[2019-03-16 13:17:18] [/SEVERE]: An unexpected error occurred
enchcracker.NativeException: std::bad_alloc: std::bad_alloc
	at enchcracker.NativeSingleSeedCracker.nfirstInput(Native Method)
	at enchcracker.NativeSingleSeedCracker.firstInput(NativeSingleSeedCracker.java:60)
	at enchcracker.EnchCrackerWindow$3.lambda$1(EnchCrackerWindow.java:283)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by asquared31415** [comment]
This is commonly caused when the cracker can't allocate the required memory.  Try increasing the memory allocated to the cracker in the .bat file by ~1GB

**Comment by Earthcomputer** [comment]
If this is still an issue, reply and I can reopen.
