### ISSUE TITLE
I am a mac user. Ran the following line of code in terminal, caused an UnsupportedClassVersionError.

### ISSUE THREAD

**Issue by shenkuo994** [Earthcomputer/EnchantmentCracker#63]
Code: java -Xmx4g -jar /Users/ps/Desktop/enchcracker/enchcracker.jar

Response:

Exception in thread "main" java.lang.UnsupportedClassVersionError: enchcracker/EnchCrackerWindow : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

[Process completed]

**Comment by MCRcortex** [comment]
im 90% sure this only works on windows

**Comment by Earthcomputer** [comment]
That's not it. You need to update Java.
