### ISSUE TITLE
Native library not loading on Linux

### ISSUE THREAD

**Issue by mn014** [Earthcomputer/EnchantmentCracker#84]
enchcracker.log:
[2019-07-24 18:47:23] [/INFO]: System details:
[2019-07-24 18:47:23] [/INFO]: OS = Linux 5.2.1-arch1-1-ARCH
[2019-07-24 18:47:23] [/INFO]: Arch (either OS/Java) = amd64
[2019-07-24 18:47:23] [/INFO]: Java = 1.8.0_222
[2019-07-24 18:47:23] [/INFO]: Java arch = 64
[2019-07-24 18:47:23] [/WARNING]: Failed to load native enchcracker library! Using the Java version instead
java.lang.UnsatisfiedLinkError: no enchcracker in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:18)
        at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:110)

I tried to repair this myself by trying various fixes proposed in Windows 10 issue as well as Mac OS issues. Nothing helped. I was trying to launch program by ./enchcracker.sh as well as "java -jar <file>"

**Comment by Earthcomputer** [comment]
Try `LD_LIBRARY_PATH=. ./enchcracker.sh`

**Comment by Earthcomputer** [comment]
Fixed in version 1.4... with the removal of the native library ;)
