### ISSUE TITLE
Error while running on OSX

### ISSUE THREAD

**Issue by LANKDORD** [Earthcomputer/EnchantmentCracker#88]
I tried to run the OSX version but I get this error every time no matter what I do ! 

[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/3445141/enchcracker.log)

][2019-07-30 14:14:54] [/INFO]: System details:
[2019-07-30 14:14:54] [/INFO]: OS = Mac OS X 10.13.6
[2019-07-30 14:14:54] [/INFO]: Arch (either OS/Java) = x86_64
[2019-07-30 14:14:54] [/INFO]: Java = 12.0.1
[2019-07-30 14:14:54] [/INFO]: Java arch = 64
[2019-07-30 14:14:54] [/WARNING]: Failed to load native enchcracker library! Using the Java version instead
java.lang.UnsatisfiedLinkError: /Users/wales/Desktop/Minecraft/enchcracker/libenchcracker.jnilib: dlopen(/Users/wales/Desktop/Minecraft/enchcracker/libenchcracker.jnilib, 1): no suitable image found.  Did find:
	/Users/wales/Desktop/Minecraft/enchcracker/libenchcracker.jnilib: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/wales/Desktop/Minecraft/enchcracker/libenchcracker.jnilib: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2653)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
	at java.base/java.lang.System.loadLibrary(System.java:1902)
	at enchcracker.NativeSingleSeedCracker.initCracker(NativeSingleSeedCracker.java:18)
	at enchcracker.EnchCrackerWindow.main(EnchCrackerWindow.java:110)

Thanks man, big fan.

**Comment by Earthcomputer** [comment]
After some research this looks like a bug. I'm not entirely sure how to fix it, but it will be circumvented in the next release anyway with the removal of the native component.

**Comment by luvletter2333** [comment]
I got this too lol

**Comment by Earthcomputer** [comment]
This should be fixed in version 1.4
