### ISSUE TITLE
Enchantment Cracker sometimes crashes if you go from second tab to first tab

### ISSUE THREAD

**Issue by Earthcomputer** [Earthcomputer/EnchantmentCracker#9]
See video:

https://youtu.be/siBLyX6OFtw
Bug 1... finished to get my first Exp seen... entered the numbers and went back to the Exp seend.. it crashed

(split from #8)

**Comment by Earthcomputer** [comment]
@NintendoBest

**Comment by NintendoBest** [comment]
[2018-04-09 09:20:40] [/INFO]: Reduced possible seeds to 6
[2018-04-09 09:20:53] [/INFO]: Added info, b = 10, s1 = 3, s2 = 9, s3 = 20
[2018-04-09 09:20:53] [/INFO]: Reduced possible seeds to 1
[2018-04-09 09:21:44] [/INFO]: Reset the cracker
[2018-04-09 09:21:51] [/INFO]: Calculate player seed failed, XP seed invalid
[2018-04-09 09:23:20] [/SEVERE]: An unexpected error occurredjava.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Unknown Source)
	at java.awt.Component.getLocationOnScreen(Unknown Source)
	at javax.swing.text.JTextComponent$InputMethodRequestsHandler.getTextLocation(Unknown Source)
	at sun.awt.im.InputMethodContext.getTextLocation(Unknown Source)
	at sun.awt.windows.WInputMethod$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Earthcomputer** [comment]
Caused by this, maybe?
[https://bugs.openjdk.java.net/browse/JDK-8186432](https://bugs.openjdk.java.net/browse/JDK-8186432)

**Comment by Earthcomputer** [comment]
Having looked into it further, this is a bug in Java itself, which means I'll have to just work around it. It was introduced in 8u131 and fixed in b172.

**Comment by Earthcomputer** [comment]
I think I've fixed it, although, as I said I haven't been able to test it. If you encounter this issue again, just reply to this and I'll re-open this issue.

**Comment by NintendoBest** [comment]
Still occuring. Btw. it doesn't matter which tab you go next... just clicking 'Reset cracker, go to Player seed, minimize, and then then try to change to an other tab will crash.

However. Now there is a life saver because it's saying before closing that a fatal error occured, so you can recover the player seed before closing.

**Comment by Earthcomputer** [comment]
I don't think another video for this is required. If you look in the log files, do you get the same error as before or a different error? The error is happening somewhere in one of the text fields.

**Comment by NintendoBest** [comment]
same error log.

**Comment by Earthcomputer** [comment]
How about version 1.1.3?
